### ISSUE TITLE
Sync ensemble forecasts on THREDDS

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#313] opened 2020-11-10 14:35 UTC
## Description

ECCC produces ensemble forecasts and distributes them through GeoMET and their datamart. The original plan was to fetch data from GeoMET using WCS directly in netCDF format, but the metadata fields are empty and there is no scheduled fix for this. 

The solution for now would be to fetch files from the "datamart". 

Create cron job to do the following every day at 7h and 19h.

- Copy to temporary directory files from 
   - https://dd.weather.gc.ca/ensemble/geps/grib2/raw/??/???/CMC_geps-raw_TMP_TGL_2m_latlon0p5x0p5_*_P*_allmbrs.grib2 
   - https://dd.weather.gc.ca/ensemble/geps/grib2/raw/??/???/CMC_geps-raw_APCP_SFC_0_latlon0p5x0p5_*_P*_allmbrs.grib2
- Convert files to netCDF(see below)
- Copy netCDF files on THREDDS to `Birdhouse/eccc/ensemble/geps`
- Clean old netCDF files

The `??/????` in the path refer to the 0-h of the forecast (00 or 12), and the forecast lead time (increments of 3-h then 6-h). 

Also (Travis)
- Create NcML to aggregate variables and time. Note that there are two *time* dimensions, one for the time the forecast was issued, and another for the forecast time. 

If this all works fine, we would follow a similar model to host other ensemble products (REPS, GDPS, RDPS).

### Notes
`CMC_geps-raw_TMP_TGL_2m_latlon0p5x0p5_2020110900_P000_allmbrs.grib2`
`_____________VAR______________________YYYYMMDDHH_PFTS_________`

where `YYYYMMDD` is the date and time the forecast was made, and `FTS` is the forecast lead time. Now that for precipitation, the first forecast is at 003 because it is the cumulative precipitation from time 00. 

Note that there are 65 3-h time steps followed by 25 6-h time steps. 

### Conversion to netCDF
$ pip install xarray cfgrib

```python
import xarray as xr

def convert(fn):
  """Convert grib2 file to netCDF format.

  TODO: Add parameter to change output directory.
  """
  ds = xr.open_dataset(fn, engine="cfgrib", backend_kwargs={'filter_by_keys':{'dataType': 'cf'}})
  ds.to_netcdf(fn.replace(".grib2", ".nc"))
```

**Comment by tlogan2000** [comment] 2020-11-11 19:13
@huard python code for retrieving and converting should go in `utilities`?

**Comment by huard** [comment] 2020-11-11 19:22
I suggest to keep it separate from raven. I think it could be a single file, possibly in pavics-sdi.

**Comment by tlogan2000** [comment] 2020-11-11 19:23
ok

**Comment by tlogan2000** [comment] 2020-11-11 21:10
we may want to look at using a subscription service?  https://eccc-msc.github.io/open-data/msc-datamart/amqp_en/ 

seems a bit complex but could simplify things for other datasets longterm

**Comment by tlogan2000** [comment] 2020-11-12 14:55
For the subscription service : 
a `test.conf` file with the following seems like it should work but I can't seem to get anything actually running/downloading
@tlvu @huard  anyone have time to take a second look at the documentation ?https://github.com/MetPX/sarracenia/blob/master/doc/subscriber.rst#revision-record

````
broker amqps://anonymous@dd.weather.gc.ca
subtopic ensemble.geps.grib2.raw
directory /tmp
accept .*CMC_geps-raw_TMP_TGL_2m_latlon0p5x0p5_.*_P.*_allmbrs.*.#
accept .*CMC_geps-raw_APCP_SFC_0_latlon0p5x0p5_.*_P.*_allmbrs.*.#
````
````
% sr_subscribe add test  
% sr_subscribe start test
````

**Comment by richardarsenault** [comment] 2020-11-13 00:23
Is it possible that there is a hashtag missing after:
```
subtopic ensemble.geps.grib2.raw
subtopic ensemble.geps.grib2.raw#
```
In the examples they have it as so for the GDPS:
`subtopic model_gem_global.25km.grib2.#`

They also seem to recommend downloading multiple at a time:
`instances 5
`

Their example file:
```
# Fichiers GRIB pour le SRPD 15km
# Pour plus d'information sur ce produit, veuillez consulter la documentation a
#  http://weather.gc.ca/grib/grib2_reg_15km_f.html

broker amqps://dd.weather.gc.ca/

# RDPS 15km GRIB files
# For more information about this product, please consult the documentation at 
# http://weather.gc.ca/include/lang.php

#instances:
#    quantité de processus qui téléchargent simultanément. 
instances 5
#instances: These files are large, so downloading them one after the other is slow.
# with higher number, download several at a time.

# la téléchargement de sarracenia est optimale pour beaucoup de petits fichiers. C´est
# miuex pour les gros fichier d´utiliser une téléchargeur binaire, tel que wget.
plugin accel_wget
# sarracenia built-in downloader works best for large numbers of small files.
# for larger files, a binary downloader will be faster.

#expire, en usage opérationnel, c´est mieux 1d (1 jour) pour celui-ci. Il faut que ça soit plus long que l´interruption le plus long qu´on veut toléré sans perte.
expire 10m
#expire, in operational use, use 1d (1 day) as it needs to be longer than the longest interruption in downloads we want to tolerate without dropping downloads.

subtopic model_gem_global.25km.grib2.#
accept .*
```

What ours would look like:

```
broker amqps://anonymous@dd.weather.gc.ca
instances 5

plugin accel_wget

# Set to 10m for tests but they recommend longer, such as 1d.
expire 10m

subtopic ensemble.geps.grib2.raw#
directory /tmp
accept .*CMC_geps-raw_TMP_TGL_2m_latlon0p5x0p5_.*_P.*_allmbrs.*.#
accept .*CMC_geps-raw_APCP_SFC_0_latlon0p5x0p5_.*_P.*_allmbrs.*.#

```
Hope this can be useful!

Thanks a lot for working on this!

**Comment by tlogan2000** [comment] 2020-11-13 13:37
@richardarsenault  did you actually get this to start downloading files?  Everything seems to start up fine for me (no errors) but am not seeing any actual files coming in ... will keep trying in a bit

**Comment by richardarsenault** [comment] 2020-11-13 13:59
No, I didn't try, I just looked at the docs.

**Comment by tlogan2000** [comment] 2020-11-13 16:52
Getting files now ... i think the accept lines should not use the end hashtag
````
broker amqps://dd.weather.gc.ca/

# GEPS Ensemble forecast GRIB files

#instances:
#    quantité de processus qui téléchargent simultanément.
instances 3
# instances: number of downloading processes. overlap multiple downloads for higher performance.

# le téléchargement de sarracenia est optimal pour beaucoup de petits fichiers. C´est
# mieux pour les gros fichiers d´utiliser un téléchargeur binaire, tel que wget.
plugin accel_wget
# larger files use binary downloader, rather than built-in processing.

#expire, en usage opérationnel, c´est mieux 1d (1 jour) pour celui-ci. Il
#        faut que cela soit plus long que l´interruption la plus longue tolérée sans perte.
expire 10m
# expire, in operations, needs to be longer than the longest expected interruption in service.
#       suggest 1d (1 day.)
directory /tmp/output
subtopic ensemble.geps.grib2.raw.#
accept .*TMP_TGL.*.grib2
accept .*APCP_SFC.*.grib2
````

**Comment by richardarsenault** [comment] 2020-11-13 16:54
Oh yeah, good catch, missed that. Good news then!

Please let me know what the format looks like (ex: does it all come in folders per forecast timestep? Is it devided by forecast issue time? etc. 

Thanks! Good progress right here.

**Comment by richardarsenault** [comment] 2020-11-13 18:32
In our case I think it would probably be simpler to get everything in the same folder, just to simplify the tree. Or else you'll get 2 files per folder, and like 160 folders or something like that. To me it does not change anything since at the end I think I'll just need to interact with the ncml? In which case, do what is easiest for you.

**Comment by tlogan2000** [comment] 2020-11-13 20:47
Pretty good progress here : with the subscription service running I should get new files pulled automatically (I will leave running over the weekend to make sure I get expected behavior)

For conversion : a cron job could be set up on the following python code (could be run multiple times a day -- performance is pretty good ... see notes below)   

````
import xarray as xr
from pathlib import Path
import multiprocessing as mp
import itertools as it
import tempfile
import shutil
import time
jobs = dict(GEPS=dict(inpath=Path('/home/logan/github/raven/tmp/output'),outpath=Path('/home/logan/github/raven/tmp/output/netcdf')))
def main():
    for j in jobs:
        time1 = time.time()
        infiles = sorted(list(jobs[j]['inpath'].rglob('*.grib2')))

        # only convert files that do not exist already
        infiles = [i for i in infiles if not jobs[j]['outpath'].joinpath(i.name.replace('.grib2','.nc')).exists()]

        combs = list(it.product(*[infiles,[jobs[j]['outpath']]]))
        pool = mp.Pool(25)
        pool.map(convert,combs)
        pool.close()
        pool.join()

        print('done' , j , 'time : ', time.time()-time1)

def convert(fn):
  """Convert grib2 file to netCDF format.

  infile, outpath = fn

  if not outpath.exists():
      outpath.mkdir(parents=True)
  ds = xr.open_dataset(infile, engine="cfgrib", backend_kwargs={'filter_by_keys':{'dataType': 'cf'}})
  encoding = {var: dict(zlib=True) for var in ds.data_vars}
  tmpfile = tempfile.NamedTemporaryFile(suffix='.nc', delete=False)
  ds.to_netcdf(tmpfile.name, encoding=encoding)
  shutil.move(tmpfile.name,outpath.joinpath(infile.name.replace(".grib2", ".nc")).as_posix())
if __name__ == '__main__':
    main()
````

Notes:

- Individual files are tiny :  running on my VM with 4 cores and ~8GB ram I could convert 25 concurrent files without any issues

- With this setup total conversion of ~1200 files took ~4 minutes (with limited VM resources)

- Adding zlib compression shrinks individual .nc to a fraction of .grib2 file size ( ~1/10th)

Question : how long of an archive do we want to provide?  Currently I see forecasts with dates of 20201110 to 20201112.  But files will continue to accumulate in the output netcdf folder unless I decide to delete older ones

**Comment by tlogan2000** [comment] 2020-11-13 20:58
@richardarsenault @huard  APCP files has data variable of `paramId_0` is this as expected? 
For reference TMP_TGL has `t2m` which seems more appropriate

**Comment by richardarsenault** [comment] 2020-11-13 22:09
Good question. I'll ask @julemai to chime in as she has more experience than I do using ECCC forecasts, I've always used versions that had been previously processed to netcdf so I am unfamiliar with the base product.

As for the number of days to keep in "reserve", I expect we won't need that many, maybe 2-3 tops. Eventually we might want to do something to bridge the gap between, say, the 2-3 week lag of Caspar automatic retrievals and the current-day forecasts, but I need to think about this a bit.

**Comment by richardarsenault** [comment] 2020-11-16 18:28
@tlogan2000 did the query perform as expected during the weekend? If so, can we start thinking about the format that the data will be stored under? i.e. ncml with a fixed path and filename related to the forecast date? If we can determine the best way forward I can adapt my forecasting codes ASAP.

**Comment by tlogan2000** [comment] 2020-11-16 20:19
I got new files over the weekend! We can maybe schedule a meeting this week to discuss output format?

**Comment by richardarsenault** [comment] 2020-11-17 00:52
> APCP files has data variable of `paramId_0` is this as expected?
> For reference TMP_TGL has `t2m` which seems more appropriate

I've checked with @julemai and it seems that it is normal, ECCC simply does not provide a descriptive variable name for the precip.

However, the precip is in meters "m" and is cumulative. @huard, we can leave it that way in cumulative because Raven can handle it, but in that case we need to add a flag in the template, which I think can be done pretty easily?

**Comment by julemai** [comment] 2020-11-17 00:54
The flag is `:Deaccumulate`. Somewhere in the same block where you put `:TimeShift` and `:LinearTransform`

**Comment by tlogan2000** [comment] 2020-11-17 16:01
> ```python
> backend_kwargs={'filter_by_keys':{'dataType': 'cf'}}
> ```

@richardarsenault  @huard PVI changing to `{filter_by_keys:{'dataType':'pf'}}`  let's me access 20 runs instead of one.  (My reduced filesize comment is most likely no longer relevant!!)

Q : Is there any documentation on this dataset anywhere?  I'm not sure what i'm pulling with`'cf'` versus `'pf'` etc it would be nice to know

**Comment by tlogan2000** [comment] 2020-11-17 16:06
https://apps.ecmwf.int/codes/grib/format/mars/type/

cf = control forecast
pf = perturbed forecast

**Comment by richardarsenault** [comment] 2020-11-17 16:10
Yes that is correct. For now, pf is preferred, but eventually we might want to upgrade to both, to get the 21 member ensemble.

**Comment by richardarsenault** [comment] 2020-11-24 19:14
@huard Deaccumulate

**Comment by tlogan2000** [comment] 2020-11-24 21:22
@huard @richardarsenault   two ncmls to test / validate on the server:

https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/geps_forecast/2020112200_test.ncml
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/geps_forecast/2020112212_test.ncml

I will be looking at cleaning up the code / deploying on the server with long next week sometime

**Comment by huard** [comment] 2020-11-24 22:06
I'm getting this error
```python
>>> ds = xr.open_dataset("https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/geps_forecast/2020112212_test.ncml")
>>> pr = ds.pr.isel(lat=45, lon=450, member=0)
oc_open: server error retrieving url: code=? message="Error {
    code = 500;
    message = "NcSDArray InvalidRangeException=Illegal Range for dimension 0: last requested 96 > max 95";
}"
```

**Comment by tlogan2000** [comment] 2020-11-24 22:30
> ```python
> ds.pr.isel(lat=45, lon=450, member=0)
> ```

@huard This might be a thredds cache / bandwidth thing? Can you confirm that setting `chunks='auto'` solves issue?
````
ds = xr.open_dataset("https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/geps_forecast/2020112212_test.ncml", chunks='auto')
````

**Comment by huard** [comment] 2020-11-25 13:57
Same error.

**Comment by tlogan2000** [comment] 2020-11-25 14:01
Ok that's weird asi it seems to work on my end.. Will try to dig into it more

Another option : the NcML layer might be an unnecessary layer of complexity in this case.  There are only two files per forecast date after my conversion script is finished running ( 1 per variable) ...  Any objection to me merging tas, pr into a single .nc and  just accessing via thredds normally?

**Comment by huard** [comment] 2020-11-25 14:15
If it works on your end, the problem must be on my end. What is your version of xarray and pydap?

**Comment by tlogan2000** [comment] 2020-11-25 14:23
xarray == 0.16.1
pydap not installed?

**Comment by tlogan2000** [comment] 2020-11-25 14:23
I do get the error without applying chunking so there might be something wrong.

**Comment by tlogan2000** [comment] 2020-11-25 14:29
Getting your error today... something need to be tuned

**Comment by huard** [comment] 2020-11-25 14:34
Good, at least we get consistent errors. 
`ncdump -h` says
```
dimensions:
	lat = 361 ;
	lon = 720 ;
	member = 20 ;
	time = 97 ;
```
So there seem to be a mistake in the time dimension interpreted by NcML.

**Comment by huard** [comment] 2020-11-25 14:37
I think I got it. The time steps for pr and tas might be different. pr is accumulated precip, so there is no first time step. There might be an additional time step at the end.

**Comment by tlogan2000** [comment] 2020-11-25 14:38
Yep. I think i might need to ensure that tas and pr files have identical / commeon timesteps before creating the ncml
timestep of individual files:
pr == 96
tas == 97

**Comment by huard** [comment] 2020-11-25 14:41
I suggest adding a pr timestep at the first step with all values set to 0.

**Comment by richardarsenault** [comment] 2020-11-25 14:52
sorry I'm late to the party, but yes, the precip has one fewer time steps as the accumulation is from timestep 0-3, so timestep 0 does not exist. Adding it manually would probably be the easiest and safest option in my opinion.

**Comment by richardarsenault** [comment] 2020-11-26 03:49
Also, not sure why but the times I get are really weird: 

```
ds.pr.time

<xarray.DataArray 'time' (time: 97)>
array(['2020-11-22T12:01:04.000000000', '2020-11-22T15:00:16.000000000',
       '2020-11-22T17:59:28.000000000', '2020-11-22T21:00:48.000000000',
       '2020-11-23T00:00:00.000000000', '2020-11-23T02:59:12.000000000',
       '2020-11-23T06:00:32.000000000', '2020-11-23T08:59:44.000000000',
       '2020-11-23T11:58:56.000000000', '2020-11-23T15:00:16.000000000',
       '2020-11-23T17:59:28.000000000', '2020-11-23T21:00:48.000000000',...])
```
Is it possible to round them to the nearest hour? Clearly they're very close but this will be unusable I think for Raven, which needs exact timedeltas between timesteps.

**Comment by tlogan2000** [comment] 2020-11-26 13:33
> Also, not sure why but the times I get are really weird:
> 
> ```
> ds.pr.time
> 
> <xarray.DataArray 'time' (time: 97)>
> array(['2020-11-22T12:01:04.000000000', '2020-11-22T15:00:16.000000000',
>        '2020-11-22T17:59:28.000000000', '2020-11-22T21:00:48.000000000',
>        '2020-11-23T00:00:00.000000000', '2020-11-23T02:59:12.000000000',
>        '2020-11-23T06:00:32.000000000', '2020-11-23T08:59:44.000000000',
>        '2020-11-23T11:58:56.000000000', '2020-11-23T15:00:16.000000000',
>        '2020-11-23T17:59:28.000000000', '2020-11-23T21:00:48.000000000',...])
> ```
> 
> Is it possible to round them to the nearest hour? Clearly they're very close but this will be unusable I think for Raven, which needs exact timedeltas between timesteps.

ok . I look at that while patching the precip timesteps

**Comment by tlogan2000** [comment] 2020-11-26 20:13
> I suggest adding a pr timestep at the first step with all values set to 0.
@richardarsenault @huard 
If first precip time step is all `nan` is that ok?

**Comment by huard** [comment] 2020-11-26 20:46
No, because the Raven model does pr(t+1) - pr(t) to find the precip flux.

**Comment by tlogan2000** [comment] 2020-11-26 20:48
> No, because the Raven model does pr(t+1) - pr(t) to find the precip flux.

ignoring nans though?

**Comment by tlogan2000** [comment] 2020-11-26 20:48
I think I figured out how to pad with zeros anyway

**Comment by tlogan2000** [comment] 2020-11-26 21:12
New version to test..  I think everything is ok nb these are nto ncmls. I simply have combined tas, pr in a single netcdf.
A straight 1to1 ncml mapping could potentially be done if we want to bother... not sure if there is added value in doing that

````
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/geps_forecast/CMC_geps-raw_latlon0p5x0p5_2020112200_allP_allmbrs.nc

https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/geps_forecast/CMC_geps-raw_latlon0p5x0p5_2020112212_allP_allmbrs.nc
````

**Comment by huard** [comment] 2020-11-26 21:41
Works like a charm on my end. 

Agreed. No value in adding an NcML layer for now. 

Thanks !

**Comment by richardarsenault** [comment] 2020-11-27 12:48
Works for me, I was able to access those data on THREDDS and write the forecasting code with success. So, good news overall!

Only thing is that, say for the 2020-11-23-00 forecast, the ncml only includes tas. Then, for Nov 24-26, there were no ncmls files.

I am guessing that this is just because the latest version did not have a chance to be rolled out and actually download and merge data since then?

Thanks!

**Comment by huard** [comment] 2020-11-27 13:17
@tlogan2000 Having second thought about NcMLs. The value of the NcML is in having a static link that does not change, but get's you the "latest" forecast. This is in contrast to the file names, that will change every day, no ?

**Comment by tlogan2000** [comment] 2020-11-27 13:42
> @tlogan2000 It would be useful I think to have a "latest" link, either with NcML or straight netCDF symbolic link.

ok we can look into having a single 'current' ncml that changes underlying data location at each update.   The previous ncfiles can remain for ~3 weeks or so ... @richardarsenault said caspar update every 2 weeks or so ... so we shouldn't have any gaps

**Comment by tlogan2000** [comment] 2020-11-27 13:44
> Works for me, I was able to access those data on THREDDS and write the forecasting code with success. So, good news overall!
> 
> Only thing is that, say for the 2020-11-23-00 forecast, the ncml only includes tas. Then, for Nov 24-26, there were no ncmls files.
> 
> I am guessing that this is just because the latest version did not have a chance to be rolled out and actually download and merge data since then?
> 
> Thanks!

@richardarsenault I stopped getting the updates occasionally as I was getting a lot of data .... I want to fine tune on just a couple of forecast dates then we will start 'production' where everything should keep coming in

**Comment by tlogan2000** [comment] 2020-11-27 13:47
> 2020-11-23-00 forecast tas only 
I think you might have been accessing a 'running' conversion.... i might need to write to a tmp location then move to the thredds to avoid users seeing 'partially converted'  files like this

**Comment by tlogan2000** [comment] 2020-11-30 13:56
@richardarsenault @huard  couple of updates:

- The subscription service seems a bit unreliable in the end... I ended up with a relatively large number of missing files in my download folder which were available on the datamart.   So  I have implemented a download function that can be called before conversion is done.  Disadvantage is that it does not run in the background but could potentially be called in a separate cron job every couple of hours if we wanted?

- Thursday outputs are extended forecasts (twice as many time steps) ... do we keep all of them or do we want to limit to the 'normal' 96 timesteps

**Comment by richardarsenault** [comment] 2020-11-30 14:01
@tlogan2000 Alright, thanks for the update.

- That's a bummer. Yes, perhaps a cron job that can do the job and runs regularly would be a simple enough option? I'll let @huard see what's the best approach.

- I think we can keep the timesteps fixed and not use the extended S2 forecasts, I don't think it's that useful for now. Maybe eventually we'll want to add that option, but right now I would say it's out of scope.

Thanks!

**Comment by huard** [comment] 2020-11-30 14:04
@tlogan2000 I'll defer to Long on what should be the most robust way to fetch those files.

**Comment by tlogan2000** [comment] 2020-11-30 18:22
FYI I have meeting with Long tomorrow so will try to plan a transition to getting this running operationally

**Comment by tlogan2000** [comment] 2020-12-01 19:58
@huard @richardarsenault  Test version of 'latest' ncml here:
https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/geps_forecast/GEPS_latest.ncml

**Comment by huard** [comment] 2020-12-01 20:31
Works like a charm here.

**Comment by richardarsenault** [comment] 2020-12-02 20:50
Same here! works great!

**Comment by huard** [comment] 2020-12-02 20:56
Ping @cjauvin

**Comment by tlogan2000** [comment] 2020-12-02 20:59
@huard @cjauvin I think the final locations might change for the "current ncml" as well as the netcdfs.  I.e. Do we want this deployed on https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/catalog.html   with a new 'forecast' folder?

Right now I am dumping everything in 'testdata' in the parent birdhouse folder

**Comment by richardarsenault** [comment] 2020-12-04 02:08
@tlogan2000 How complicated would it be to also fetch the deterministic GDPS run from here: https://dd.weather.gc.ca/model_gem_global/15km/grib2/lat_lon/00/003/

for files (should be same file structure as GEPS):

CMC_glb_APCP_SFC_0_latlon.15x.15_2020120300_P003.grib2 
CMC_glb_TMP_TGL_2_latlon.15x.15_2020120300_P003.grib2 

And do the same ncml treatment as before?

This would allow me to also check the "deterministic forecast" box for the development phase.

Thanks!

**Comment by tlogan2000** [comment] 2020-12-04 13:19
This should be pretty similar to the geps so should be doable... I suggest getting the geps running smoothly on the server first then diving into this

**Comment by richardarsenault** [comment] 2020-12-04 13:21
perfect, thanks!

**Closed** 2021-03-27 19:04 UTC
