### ISSUE TITLE
Emulate MOHYSE in Raven (4)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#11] opened 2018-05-31 00:57 UTC

**Comment by richardarsenault** [comment] 2018-08-13 14:34
Julie will integrate MOHYSE into RAVEN with the help of James Craig.

**Comment by julemai** [comment] 2018-09-12 14:44
James Craig's evaluation of MOHYSE in RAVEN:

#Translation of MOHYSE model into Raven:
 
```
  :PotentialMelt     POTMELT_DEGREE_DAY
  :CatchmentRoute    ROUTE_GAMMA_CONVOLUTION2
  :EvaporationMethod PET_MOHYSE
  :DirectEvaporation DIRECT_EVAP_BASIC
 
  :HydrologicProcesses
     :SoilEvaporation  SOILEVAP_LINEAR  SOIL[0]      ATMOSPHERE
     :SnowBalance      SIMPLE_MELT      SNOW         PONDED_WATER
     :Precipitation    RAVEN_DEFAULT    ATMOS_PRECIP MULTIPLE
     :Infiltration     INF_HBV          PONDED_WATER SOIL[0]
     :Baseflow         BASE_LINEAR      SOIL[0]      SURFACE_WATER
     :Percolation      PERC_LINEAR      SOIL[0]      SOIL[1]
     :Baseflow         BASE_LINEAR      SOIL[1]      SURFACE_WATER
  :EndHydrologicProcesses
```
 
#linear infil: equal to inf HBV with beta=1 or VIC_ARNO with b=1
 
TODO:

1. Add SOILEVAP_LINEAR  # should have anyhow
2. Add PET_MOHYSE (or find literature source for better name)
3. Support :DirectEvaporation which reduces rain & PET simultaneously prior to ponding as forcing correction [defaults to DIRECT_EVAP_NONE]
4. Add ROUTE_GAMMA_CONVOLUTION2 to be able to override shape parameter of UH

All of these are very straightforward revisions (at least for James :) )

**Comment by julemai** [comment] 2018-09-12 14:44
@huard I have a meeting with James Craig about this topic tomorrow. So, I will update you by tomorrow.

**Comment by julemai** [comment] 2018-09-13 17:49
@huard The meeting with James was very fruitful. We will start with the implementations of this model (rather than HMETS). You estimate is reasonable. Probably a little too high. We will have this running for our meeting in October. :)

**Comment by julemai** [comment] 2018-09-13 18:00
@richardarsenault During my meeting with James, we were wondering if you have an idea where the PET formulation in MOHYSE is originating from. This [document](https://docplayer.fr/69668879-Le-modele-hydrologique-mohyse.html) isn't mentioning any reference for this. So, we would call the approach PET_MOHYSE in RAVEN.

@richardarsenault We want to compare our RAVEN implementations against the MATLAB codes. It would be great if we could use a parameterized model if you have one at hand. Otherwise I'd use one of our catchments but would need to find good parameter sets to get reasonable outputs. Let me know!

**Comment by richardarsenault** [comment] 2018-09-13 18:38
@julemai We can certainly send you parameters and data to test the MOHYSE model on one of our catchments. I'll get that to you shortly.

@julemai The PET (ETP in french) is computed in equations 2-7 and was developed by the MOHYSE creators. It was supposed to be an equation that includes most processes that can be easily understood by students, not necessarily to perform super well.

**Comment by julemai** [comment] 2018-09-13 19:04
@richardarsenault Great! I'll build up a framework then to benchmark the two versions- Raven and Matlab- against each other.

@richardarsenault Another document to improve my French. The process is going to be called PET_MOHYSE then. :)

**Comment by richardarsenault** [comment] 2018-09-21 23:19
Thanks Julie, Tell me if you need anything else.

**Comment by julemai** [comment] 2018-09-21 23:41
MOHYSE is 99.9% emulated in Raven everything. Kudos to James Craig. Raven is running with an NSE of 0.731 for the test setup. The only thing we don't want to emulate is that MOHYSE allows for negative AET/soil moisture. That's the reason for the slight difference. The new version will be pushed to the Raven trunk on Monday.

I would show all the detailed results and how to setup Raven in MOHYSE-mode when we meet beginning of October. How does that sound?

**Comment by richardarsenault** [comment] 2018-09-21 23:54
Sounds good, that is great news! Say thanks to James for me!

Would it be easy for you to provide a code to run GR4J with CemaNeige ? We could start testing with that test case for now, for example with regionalization and calibration.

Thanks!

**Comment by julemai** [comment] 2018-09-22 00:02
Yep. That setup should actually be in the manual of Raven. I have one example for GR4J for the York watershed. I will double-check with James on Monday if this has GR4J and Cemaneige properly setup and then I'll share it with you. 

If you prefer one of your basins please send it to me and I use that one.

**Comment by richardarsenault** [comment] 2018-09-22 00:19
Hi, no problem for the catchment, it's more about the logic of connecting everything in the pavics framework than actually modelling anything interesting... 
Thanks a lot! 
Richard 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Julie <notifications@github.com> Date: 2018-09-21  20:02  (GMT-05:00) To: Ouranosinc/raven <raven@noreply.github.com> Cc: richardarsenault <richard.arsenault@etsmtl.ca>, Mention <mention@noreply.github.com> Subject: Re: [Ouranosinc/raven] Emulate MOHYSE in Raven (4) (#11) 
Yep. That setup should actually be in the manual of Raven. I have one example for GR4J for the York watershed. I will double-check with James on Monday if this has GR4J and Cemaneige properly setup and then I'll share it with you.
If you prefer one of your basins please send it to me and I use that one.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ouranosinc/raven","title":"Ouranosinc/raven","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Ouranosinc/raven"}},"updates":{"snippets":[{"icon":"PERSON","message":"@julemai in #11: Yep. That setup should actually be in the manual of Raven. I have one example for GR4J for the York watershed. I will double-check with James on Monday if this has GR4J and Cemaneige properly setup and then I'll share it with you. \r\n\r\nIf you prefer one of your basins please send it to me and I use that one. "}],"action":{"name":"View Issue","url":"https://github.com/Ouranosinc/raven/issues/11#issuecomment-423700119"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ouranosinc/raven/issues/11#issuecomment-423700119",
"url": "https://github.com/Ouranosinc/raven/issues/11#issuecomment-423700119",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Ouranosinc/raven] Emulate MOHYSE in Raven (4) (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Julie**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@julemai",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Ouranosinc/raven\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Ouranosinc/raven\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Ouranosinc/raven/issues/11#issuecomment-423700119"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340850537\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by julemai** [comment] 2018-09-24 22:14
MOHYSE documentation is added to the [Wiki](https://github.com/Ouranosinc/raven/wiki/Technical-Notes#raven-example-setup-for-mohyse).

Matlab runs with NSE = 0.732655
Raven runs with NSE = 0.731842

**Comment by huard** [comment] 2018-10-18 23:59
I suggest we close this issue when a new release of RAVEN includes the MOHYSE emulator.

**Comment by richardarsenault** [comment] 2018-10-19 00:04
In theory, all we need is to get the dev version on the SVN. I doubt that a new release will be made available quickly enough for our needs?

**Comment by julemai** [comment] 2018-10-19 00:11
I think if we kindly ask James, he might release soon. But I'm guessing he wants to release MOHYSE and HMETS together and not creating two releases. 

So, I think as soon as HMETS implementation (and the PET thingy) gets resolved and confirmed, we will release.

Anyways, I think for the long-term you want to have access to the developers' code. There's this [other ticket](https://github.com/Ouranosinc/raven/issues/33#issuecomment-430661004) where I explained here how to get access. I also included it in the [wiki](https://github.com/Ouranosinc/raven/wiki/Technical-Notes#get-access-to-raven-svn).

**Comment by julemai** [comment] 2018-10-19 00:13
I can also send you a copy of the current trunk in the meanwhile....

**Comment by huard** [comment] 2018-10-19 00:15
One release for MOHYSE and HMETS sounds good ! No need for the trunk just yet for me. Will let you know when I'm at that point.

**Comment by richardarsenault** [comment] 2018-10-19 00:46
OK great! Julie, I am looking at the HMETS code now, and it seems James is right, the version you have (and that is available on the file exchange) has the double RET calculation. No idea why it was never spotted... I have analyzed the situation and reported my opinion to François and Jean-Luc, but I suspect they will agree. 

I'll get back to you shortly but I feel that this item is 99.9% of the way to being ticked.

**Comment by julemai** [comment] 2018-10-19 00:52
Awesome!! Let me know and I will finish up documentation and template packaging ASAP. James is doing releases and he hasn’t committed the HMETS yet. But I’m sure he’s only waiting for your „go“. 

This is exciting!

**Closed** 2018-11-22 18:33 UTC
