### ISSUE TITLE
installing the "climpred" package conflicts with xarray and xskillscore

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#336] opened 2020-12-15 23:48 UTC
Installing the package "climpred" needed to analyze forecasts creates a conflict with Xarray and XskillScore. It either installs but cannot import, or installs, can import (by re-updating xarray version) but then raven server won't start.

A recipe to install this package would be great!

**Comment by richardarsenault** [comment] 2020-12-15 23:48
Assigned @Zeitsperre as @huard said you're the master of package conflicts and version pinning and such matters.

**Comment by Zeitsperre** [comment] 2020-12-16 13:35
> the master of package conflicts 

Haha, I'll see what I can do!

**Comment by Zeitsperre** [comment] 2020-12-16 13:41
@richardarsenault 

Seems pretty clear what the issue is; Raven has `xarray` pinned to 0.16.0 and `climpred`/`xskillscore` have `xarray` pinned to 0.16.1 and above. I know there are quite a few breaking changes between them. I can definitely start looking into updating this over the next few days. If I run into issues, I'll tag others in.

**Comment by huard** [comment] 2020-12-16 14:31
With https://github.com/CSHS-CWRA/RavenPy/pull/6 merged, we can allow for xarray >= 0.16

**Comment by Zeitsperre** [comment] 2020-12-16 14:44
Great! In that case, I'll try working off of that branch to integrate these new dependencies.

**Comment by Zeitsperre** [comment] 2020-12-16 21:52
I've opened a PR to add the dependency to the PR that @huard identified. Once we've moved the engine of `raven` to `RavenPy` it will be standard in the installation process. 

@richardarsenault Does that work for you?

**Comment by richardarsenault** [comment] 2020-12-16 22:02
Perfect, thanks! When that change to RavenPy occurs we can update everything and start from there. I'll do the climpred workflows after that.

**Comment by huard** [comment] 2021-01-29 15:43
Should now work with ravenpy 0.2.2

**Closed by huard** 2021-01-29 15:43 UTC
Labels: Ouranos, blocker
