### ISSUE TITLE
Wrap existing model calibration algorithms as WPS (8)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#16] opened 2018-05-31 01:01 UTC
Challenge is to connect calibration algorithms to model description through WPS to avoid the calibration algorithm having to call WPS services to get model outputs (the overhead would kill us).

**Comment by richardarsenault** [comment] 2018-08-13 14:36
OSTRICH is being provided by UWaterloo as an alternative to SpotPy for calibration. Integration with RAVEN is complete and requires only wrapping the codes in WPS. Wait for RAVEN/OSTRICH dockerization to write WPS?

**Comment by tomLandry** [comment] 2018-08-13 14:39
We are planning work for the project, starting with Dockerization of components. In any case, a technical meeting to get up to speed on these components would help.

**Comment by richardarsenault** [comment] 2018-08-13 14:45
Yes, I am planning a meeting for sometime in September. Julie and Bryan from Waterloo will be coming to Montreal for another project, I thought we could do a 2-for-1. I also posted the source codes for Raven and Ostrich in another ticket.

**Comment by julemai** [comment] 2019-01-08 16:01
@huard @richardarsenault 

I was hoping to get onto the emulation of OSTRICH during the coming weeks. A first step would be to make the OSTRICH executable available. Shall I do that (following what we do with RAVEN) or would somebody else like to do that? The source code is <a href="https://github.com/Ouranosinc/raven/wiki/raven-template-setups/Ostrich_2017-12-19_plus_progressJSON.zip" download="Ostrich_2017-12-19_plus_progressJSON.zip">here (.zip)</a> but I could also disseminate it through my webpage (as we do with RAVEN). The code is theoretically also available on Shawn Mattot's webpage but it doesn't have the feature of writing the current progress as a JSON string to a file...

Let me know.

**Comment by huard** [comment] 2019-01-08 16:15
Please go ahead. I'm fine with you hosting the most recent version of the code. Hopefully at some point a more official URL will be provided, but for the moment it's fine by me.

**Comment by julemai** [comment] 2019-01-29 01:51
Well, a `make clean` would resolve that. But I don't want to install the whole Python environment new....

And I just saw that the `make clean` isn't deleting the executables and the downloaded source codes of RAVEN (and OSTRICH). I thought you implemented that @huard ? Did that get lost somewhere?

**Comment by julemai** [comment] 2019-01-29 01:53
Changing to the following in the `Makefile` seems to do the job but I'm not sure if that makes sense;

```
.PHONY: conda_env
conda_env: anaconda
	@echo "Creating conda environment $(CONDA_ENV) ..."
	@test -d $(ANACONDA_HOME) || "$(ANACONDA_HOME)/bin/conda" create --yes -n $(CONDA_ENV) python=$(PYTHON_VERSION)
	@test -d $(ANACONDA_HOME) || "$(ANACONDA_HOME)/bin/conda" env update -n $(CONDA_ENV) -f environment.yml
```

**Comment by julemai** [comment] 2019-01-29 09:01
@huard: Could you please tell me where in the code, for example, `{run_name}` in the *.rvi gets replaced. I can't figure out where that is happening... Thanks!

**Comment by huard** [comment] 2019-01-29 13:00
> Well, a `make clean` would resolve that. But I don't want to install the whole Python environment new....
> 
> And I just saw that the `make clean` isn't deleting the executables and the downloaded source codes of RAVEN (and OSTRICH). I thought you implemented that @huard ? Did that get lost somewhere?

It's in `make clean_dev` I think.

**Comment by huard** [comment] 2019-01-29 13:00
> Changing the `conda_env` block of the `Makefile` to the following seems to do the job but I'm not sure if that makes sense:

Looks good.

**Comment by huard** [comment] 2019-01-29 13:04
Look in `models/basic.py` for the `_dump_rv` method of the `Raven` class. 

The values of the parameters are stored in the configuration dictionary for each rv, then aggregated into the `params` dictionary, then used to format the rv templates.

**Comment by julemai** [comment] 2019-01-29 15:00
> > Well, a `make clean` would resolve that. But I don't want to install the whole Python environment new....
> > And I just saw that the `make clean` isn't deleting the executables and the downloaded source codes of RAVEN (and OSTRICH). I thought you implemented that @huard ? Did that get lost somewhere?
> 
> It's in `make clean_dev` I think.

there is only:
* `envclean` (removes condo env)
* `srcclean` (removes *.pyc files)
* `distclean` (removes all files not under git)

I don't think that any of the above cleans the `src` and/or the `bin` folder.

**Comment by huard** [comment] 2019-01-29 15:19
Sorry, it's `raven_clean` but it's not shown in the make help. We'll have to add that.

**Comment by julemai** [comment] 2019-01-29 15:42
> Look in `models/basic.py` for the `_dump_rv` method of the `Raven` class.
> 
> The values of the parameters are stored in the configuration dictionary for each rv, then aggregated into the `params` dictionary, then used to format the rv templates.

Found it! Thanks.

But my `self.name` seems to be empty. I have no idea how this us set. I can't figure out where `templates` are coming from in `__init__` and then used for `configure`. Part of the problem is that the *.rv* files are required to be in a subfolder for OSTRICH.

I committed the current version of the code. I know it's a mess but I need to debug somehow. hence a lot of print statements etc...

The test `tests/test_wps_ostrich_gr4j_cemaneige.py::TestOstrichGR4JCemaNeigeProcess::test_simple` fails...

**Comment by julemai** [comment] 2019-01-29 15:57
Thanks. Just committed the current version.

The problem is in `basic_ostrich.py` line 189.

**Comment by huard** [comment] 2019-01-29 16:20
Just pushed a small change for configure to read the additional files from ostrich. 
Now you'll need to create tags such as `{par_x1_min}` in the  `ostIn.txt` file, to be able to fill them from the python interface, but that's going to be a mess, since we'll have to create different labels for the low and high values. Let me think about this.

**Comment by julemai** [comment] 2019-01-29 16:29
Your commit is now causing the following error:

```
Traceback (most recent call last):
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/j6mai/Documents/GitHub/raven/raven/processes/wps_ostrich.py", line 62, in _handler
    model.assign(name, data)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/basic_ostrich.py", line 160, in assign
    for ext, obj in self.rvobjs.items():
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/basic_ostrich.py", line 140, in rvobjs
    return {ext: getattr(self, ext) for ext in self._rvext}
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/basic_ostrich.py", line 140, in <dictcomp>
    return {ext: getattr(self, ext) for ext in self._rvext}
AttributeError: 'GR4JCN_OST' object has no attribute 'sh'
```

**Comment by huard** [comment] 2019-01-31 18:58
Ok so now it works... Look in tests/test_emulators.py for examples of direct calls to the models. 
I've also added a print out of error messages when the model fails to help with debugging. It also outputs the work directory. 

Now my question is: "How is this going to be used, and how to make that usage easy?" Ie once we've run Ostrich, I guess we want to run Raven with the same parameters but on another time series. So we should be able to get the parameters back from the ostrich output, and create a Raven model based on this. Another way to look at it would be: Can we have only one user interface (eg. GR4JCN, with a "calibrate" method that does all the work behind the scene and returns a parameter array) ?

**Comment by richardarsenault** [comment] 2019-01-31 20:09
Awesome news!
I'll look into it in greater detail sometime next week, I think Julie will work a bit on it until then. My only concern is about the raven model as we discussed. Ideally we want it to be the same for the Ostrich calibration and the rest of the platform (i.e. not 2 different versions to update and maintain). Is this an issue with your fix?

Also, I think a call to Ostrich calibration should be independent from other functions. We could call it in a workflow, for example, but it would be complex to launch (in a single command) calibration on a catchment, and then run the model with parameters on another dataset. My take is that we should keep it independent, return PARAMS and QSIM when we're done (on the calibration timeseries) and the user can decide what he/she wants to do with it after. Could be direct call to other WPS services or within a more general workflow. Does it make sense?

**Comment by huard** [comment] 2019-01-31 20:41
Yep, Julie, it's not clear to me how I should get the parameters back. Do we need to parse them from the rvp of the best run ?

**Comment by julemai** [comment] 2019-01-31 20:46
> Awesome news!
> I'll look into it in greater detail sometime next week, I think Julie will work a bit on it until then. My only concern is about the raven model as we discussed. Ideally we want it to be the same for the Ostrich calibration and the rest of the platform (i.e. not 2 different versions to update and maintain). Is this an issue with your fix?

The raven executable is all the same. There are no two versions of Raven. 

> 
> Also, I think a call to Ostrich calibration should be independent from other functions. We could call it in a workflow, for example, but it would be complex to launch (in a single command) calibration on a catchment, and then run the model with parameters on another dataset. My take is that we should keep it independent, return PARAMS and QSIM when we're done (on the calibration timeseries) and the user can decide what he/she wants to do with it after. Could be direct call to other WPS services or within a more general workflow. Does it make sense?

I think we should definitely return parameters and Qsim of the best model run.

**Comment by julemai** [comment] 2019-01-31 20:51
> Yep, Julie, it's not clear to me how I should get the parameters back. Do we need to parse them from the rvp of the best run ?

Nope. Ostrich itself is producing the most important output file at the end called `OstModel0.txt` which contains the `obj. function value` (col 2) and the optimal parameter set (col 3 to end). The last line always contains the overall best, final parameter set.

**Comment by julemai** [comment] 2019-01-31 20:55
I am hoping to get onto this tomorrow and create the tests to check that the same results as on the Wiki get produced. Is there anything I need to have a closer look at @huard. Means some places in the code where you were not sure where to put placeholders etc?

**Comment by huard** [comment] 2019-01-31 21:15
Yep, adding placeholders in OstIn sounds good.
Also what should we test for to make sure the setup is OK and the calibration is done correctly ? For now I'm just checking that it runs. 
I can take a quick jab at getting the outputs back.

**Comment by julemai** [comment] 2019-01-31 21:18
Yep, I would double-check that the final NSE is matching the one in the Wiki (similar as I did for the RAVEN model runs). We can also double-check that the final parameter sets are matching. It should give always the same results because the `RandomSeed` is fixed right now in the `ostIn.txt`.

**Comment by huard** [comment] 2019-01-31 21:50
Ok. I'll try to implement the parameter parsing tomorrow

**Comment by julemai** [comment] 2019-01-31 21:56
Sounds good. I’ll start after you are done

**Comment by huard** [comment] 2019-02-01 13:32
Done.

**Comment by julemai** [comment] 2019-02-01 14:03
When I run `make test`, I get the following failed 8 tests... I that the same for you?

```
======================================================= FAILURES =======================================================
__________________________________________ TestOstrich.test_gr4j_with_no_tags __________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_base.py", line 48, in test_gr4j_with_no_tags
    model.configure(ost)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 159, in configure
    rvf = RVFile(fn)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 40, in __init__
    self._store_ext()
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 49, in _store_ext
    self.ext = self.fn.suffixes[0][1:]
IndexError: list index out of range
______________________________________________ TestGR4JCN_OST.test_simple ______________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_emulators.py", line 114, in test_simple
    model = GR4JCN_OST()
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 85, in __init__
    self.configure(self.templates)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 159, in configure
    rvf = RVFile(fn)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 40, in __init__
    self._store_ext()
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 49, in _store_ext
    self.ext = self.fn.suffixes[0][1:]
IndexError: list index out of range
________________________________________________ TestMOHYSE.test_simple ________________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_emulators.py", line 174, in test_simple
    np.testing.assert_almost_equal(d['DIAG_NASH_SUTCLIFFE'], -2.98165, 4)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 4 decimals
 ACTUAL: 0.194618
 DESIRED: -2.98165
------------------------------------------------- Captured stdout call -------------------------------------------------
============================================================
                        RAVEN                               
 a robust semi-distributed hydrological modelling framework 
    Copyright 2008-2018, the Raven Development Team 
                    Version 2.9 w/ netCDF
                BuildDate Dec 19 2018
============================================================
*******************************************************

WARNING: Warnings have been issued while parsing data. 
         See Raven_errors.txt for details              

*******************************************************



===============Exiting Gracefully==============
Exiting Gracefully: Successful Simulation
===============================================
===============================================
________________________________________________ TestHBVEC.test_simple _________________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_emulators.py", line 198, in test_simple
    np.testing.assert_almost_equal(d['DIAG_NASH_SUTCLIFFE'], -2.98165, 4)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 4 decimals
 ACTUAL: -0.075407
 DESIRED: -2.98165
------------------------------------------------- Captured stdout call -------------------------------------------------
============================================================
                        RAVEN                               
 a robust semi-distributed hydrological modelling framework 
    Copyright 2008-2018, the Raven Development Team 
                    Version 2.9 w/ netCDF
                BuildDate Dec 19 2018
============================================================
*******************************************************

WARNING: Warnings have been issued while parsing data. 
         See Raven_errors.txt for details              

*******************************************************



===============Exiting Gracefully==============
Exiting Gracefully: Successful Simulation
===============================================
===============================================
______________________________________________ TestRVFile.test_simple_rv _______________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_rv.py", line 16, in test_simple_rv
    assert rvf.ext == 'rvp'
AssertionError: assert 'rvc' == 'rvp'
  - rvc
  + rvp
______________________________________________ TestRVFile.test_simple_tpl ______________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_rv.py", line 24, in test_simple_tpl
    assert rvf.ext == 'rvp'
AssertionError: assert 'rvt' == 'rvp'
  - rvt
  + rvp
________________________________________________ TestRVFile.test_ostIn _________________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_rv.py", line 30, in test_ostIn
    rvf = RVFile(rvp)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 40, in __init__
    self._store_ext()
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 49, in _store_ext
    self.ext = self.fn.suffixes[0][1:]
IndexError: list index out of range
_____________________________________ TestOstrichGR4JCemaNeigeProcess.test_simple ______________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_wps_ostrich_gr4j_cemaneige.py", line 49, in test_simple
    assert_response_success(resp)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/tests.py", line 118, in assert_response_success
    assert resp.status_code == 200
AssertionError
```

**Comment by huard** [comment] 2019-02-01 14:31
Hum, no. There are errors with MOHYSE and HBVEC about bad NSE (that's ok), and the test_wps_ostrich... but other tests should pass.

**Comment by huard** [comment] 2019-02-01 14:41
I'll bet that you have files in the raven/models/ directory that should not be there and interfere with the configuration.

**Comment by huard** [comment] 2019-02-01 14:50
Or in the testdata directory for ostrich. Remove the .sh files and other directories if any.

**Comment by huard** [comment] 2019-02-01 14:57
Pushed some changes to help debugging those things. HTH

**Comment by julemai** [comment] 2019-02-01 15:18
Ok. That helped. After removing some unnecessary files I now just get 5 tests failed:
```
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_base.py", line 48, in test_gr4j_with_no_tags
    model.configure(ost)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 158, in configure
    for fn in fns:
TypeError: 'PosixPath' object is not iterable
______________________________________________ TestGR4JCN_OST.test_simple ______________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 50, in _store_ext
    self.ext = self.fn.suffixes[0][1:]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_emulators.py", line 114, in test_simple
    model = GR4JCN_OST()
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 85, in __init__
    self.configure(self.templates)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 159, in configure
    rvf = RVFile(fn)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 40, in __init__
    self._store_ext()
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/rv.py", line 53, in _store_ext
    raise ValueError(msg) from e
ValueError: 
File /Users/j6mai/Documents/GitHub/raven/raven/models/ostrich-gr4j-cemaneige/model/.DS_Store does not look like a valid Raven/Ostrich config file.
________________________________________________ TestMOHYSE.test_simple ________________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_emulators.py", line 174, in test_simple
    np.testing.assert_almost_equal(d['DIAG_NASH_SUTCLIFFE'], -2.98165, 4)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 4 decimals
 ACTUAL: 0.194618
 DESIRED: -2.98165
------------------------------------------------- Captured stdout call -------------------------------------------------
============================================================
                        RAVEN                               
 a robust semi-distributed hydrological modelling framework 
    Copyright 2008-2018, the Raven Development Team 
                    Version 2.9 w/ netCDF
                BuildDate Dec 19 2018
============================================================
*******************************************************

WARNING: Warnings have been issued while parsing data. 
         See Raven_errors.txt for details              

*******************************************************



===============Exiting Gracefully==============
Exiting Gracefully: Successful Simulation
===============================================
===============================================
________________________________________________ TestHBVEC.test_simple _________________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_emulators.py", line 198, in test_simple
    np.testing.assert_almost_equal(d['DIAG_NASH_SUTCLIFFE'], -2.98165, 4)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 4 decimals
 ACTUAL: -0.075407
 DESIRED: -2.98165
------------------------------------------------- Captured stdout call -------------------------------------------------
============================================================
                        RAVEN                               
 a robust semi-distributed hydrological modelling framework 
    Copyright 2008-2018, the Raven Development Team 
                    Version 2.9 w/ netCDF
                BuildDate Dec 19 2018
============================================================
*******************************************************

WARNING: Warnings have been issued while parsing data. 
         See Raven_errors.txt for details              

*******************************************************



===============Exiting Gracefully==============
Exiting Gracefully: Successful Simulation
===============================================
===============================================
_____________________________________ TestOstrichGR4JCemaNeigeProcess.test_simple ______________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_wps_ostrich_gr4j_cemaneige.py", line 49, in test_simple
    assert_response_success(resp)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/tests.py", line 118, in assert_response_success
    assert resp.status_code == 200
AssertionError
```

**Comment by julemai** [comment] 2019-02-01 15:38
Resolved:
```
tests/test_rv.py::TestRVFile::test_fail
```
by adjusting function `_store_ext(self)` in class `RVFile` of `rv.py` to ignore hidden files/folders:
```
    def _store_ext(self):
        try:
            self.ext = self.fn.suffixes[0][1:]
        except IndexError as e:
            if str(self.fn)[0] == '.': # hidden file with no extension or hidden folder 
                self.ext = 'None'
            else:
                msg = "\nFile {} does not look like a valid Raven/Ostrich config file.".format(self.fn)
                raise ValueError(msg) from e
```

**Comment by julemai** [comment] 2019-02-01 15:41
You were 30s faster. Haha!! Like yours better. And it works. Thanks!

**Comment by julemai** [comment] 2019-02-01 15:42
Test `TestOstrich.test_gr4j_with_no_tags` is suffering from the `.DS_Store` issue as well....

**Comment by huard** [comment] 2019-02-01 15:44
Hum, I suggest you modify the glob pattern to avoid that. I won't be able to help for the rest of the day...

**Comment by julemai** [comment] 2019-02-01 15:44
Will do. THANKS!!

**Comment by julemai** [comment] 2019-02-01 16:05
> Hum, I suggest you modify the glob pattern to avoid that. I won't be able to help for the rest of the day...

I have no idea where these files get listed, i.e. I can't identify the `glob` that needs to get adjusted

**Comment by julemai** [comment] 2019-02-01 21:32
Alright. The two tests `test_base.py::TestOstrich::test_gr4j_with_no_tags` and `test_emulators.py::TestGR4JCN_OST::test_simple` are now working.

They have both proper checks implemented that make sure that the calibration is producing the results of our references in the Wiki.

The last test `test_wps_ostrich_gr4j_cemaneige.py::TestOstrichGR4JCemaNeigeProcess::test_simple` fails but the error message is not very helpful to trace back what's happening.

Next step for me is to specify placeholders in the `ostIn.txt` and get them filled automatically...

**Comment by huard** [comment] 2019-02-01 21:54
Let's defer the WPS stuff for the end.

**Comment by julemai** [comment] 2019-02-01 22:05
I will then add the other 3 models?!

**Comment by julemai** [comment] 2019-02-03 22:49
@huard  I've done as much as I could. There are 5 tests failing right now:
```
tests/test_emulators.py::TestGR4JCN_OST::test_simple FAILED
tests/test_wps_ostrich_gr4j_cemaneige.py::TestOstrichGR4JCemaNeigeProcess::test_simple FAILED 
tests/test_wps_ostrich_hbv_ec.py::TestOstrichHBVECProcess::test_simple FAILED
tests/test_wps_ostrich_hmets.py::TestOstrichHMETSProcess::test_simple FAILED
tests/test_wps_ostrich_mohyse.py::TestOstrichMOHYSEProcess::test_simple FAILED
```

I hope you can find what is going wrong. I have added all examples and files for now. But I couldn't properly test them (checks against predefined values) because the WPS is not running. I will do that as soon as that works.

**Comment by huard** [comment] 2019-02-04 21:03
@julemai Fixed a couple of those, but not all. Rest of my week is going to be pretty busy, response time is going to be longer.

**Comment by julemai** [comment] 2019-02-05 01:13
I think I got all emulator tests now fully functional. WPS tests are still failing but the GR4J example is somehow working better than the other 4. Trying to get that done tomorrow or the day after.

**Comment by julemai** [comment] 2019-02-05 03:46
Got them all running; also WPS tests. Only one failing is `TestOstrichMOHYSEProcess.test_simple` in `test_wps_ostrich_mohyse.py`. This is due to the split of parameters and hrs-parameters in MOHYSE. I can't figure out how to resolve this. The rest works.

```
______________________________________________________ TestOstrichMOHYSEProcess.test_simple _______________________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_wps_ostrich_mohyse.py", line 66, in test_simple
    assert_response_success(resp)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/tests.py", line 121, in assert_response_success
    assert len(success) == 1
AssertionError
-------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/j6mai/Documents/GitHub/raven/raven/processes/wps_raven.py", line 56, in _handler
    data = self.tuple_inputs[name](*arr)
TypeError: __new__() takes 9 positional arguments but 11 were given
```

**Comment by huard** [comment] 2019-02-05 12:02
Done, the params contained the hrus as well. I just removed the last two items from the lower and upper parameters passed to the test. 
@richardarsenault Maybe it'd be better in terms of clarity to just scrap the hru parameters and put all the parameters in params.

**Comment by richardarsenault** [comment] 2019-02-05 13:33
I agree, I had a fun time with that also in the regionalization toolbox. I think we could handle that internally no? I.e. have the parameter set be automatically translated to the different .rvX files within the model itself?

However maybe for now we can concentrate on other things and keep that for the next phase? Thoughts?

**Comment by huard** [comment] 2019-02-05 13:47
To be clear, it works as it is now (the parameters are already automatically translated to the different rv files). My question is really from a user perspective, is it more natural to have both params and hrus, or just one set of parameters ?

**Comment by huard** [comment] 2019-02-05 14:05
Ah ! Let's put them back together then.

**Comment by julemai** [comment] 2019-02-05 14:09
Just a thought... These are parameters per HRU. Means right now (with lumped models) we have 1 HRU and 2 parameters. With more HRUs the parameter-set will grow... I always thought that this was the reason to split them. The `params` are constant (means always 8) while `hrus` are always 2x number HRUs... Not sure.

**Comment by richardarsenault** [comment] 2019-02-05 14:13
Ah I see... therefore if we get to using distributed models, this will have an impact. Sometimes in distributed models we like to force parameters for similar HRUs for example. Maybe it is better that they stay separate. For these lumped models it complexifies a bit, but for later generalization it could be better this way. 

Does that make sense @julemai ?

**Comment by julemai** [comment] 2019-02-05 14:21
I thought this was the initial reason for splitting them. But I think we didn't follow this logic all the way through for all the 4 examples. 

@huard Do you see any issues with parameter sets being of variable length for one model depending how it is discretized?

**Comment by huard** [comment] 2019-02-05 14:45
@julemai Yes, that could get hairy pretty fast. 

I suggest we defer a decision on this once we have had a discussion on multi-basin modeling.

**Comment by julemai** [comment] 2019-02-05 14:47
Sounds good.

**Comment by julemai** [comment] 2019-02-05 15:40
Glad that all this works now. Shall I open a pull request?

**Closed** 2019-02-19 17:03 UTC
