### ISSUE TITLE
Upload land-use raster database to GeoServer (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#3] opened 2018-05-31 00:44 UTC
Check metadata is clean and CF conformant.

**Comment by Zeitsperre** [comment] 2018-06-28 13:35
Did you have a specific project in mind? NRCan and USGS have country-specific data. Most of the popular projects date back a few years (< 2010) and those with global coverage don't typically have high-resolution (~0.5 Km for [MODIS](https://landcover.usgs.gov/global_climatology.php)).

Also, GeoTIFFs don't have fields for integrated metadata and GeoServer metadata doesn't allow fields for categories like facet, simulation, history, etc. I'm not sure what you mean here.

**Comment by huard** [comment] 2018-06-28 13:42
@richardarsenault ?

**Comment by Zeitsperre** [comment] 2018-08-14 17:30
@richardarsenault 
I'm also curious to see if we could clarify this matter. I can manually create NetCDF containers from GeoTIFFs but it is relatively labour-intensive. If this is data must be searchable within the facet list, we need to propose a few conventions/practices. Is there a land use raster project you already have in mind?

**Comment by Zeitsperre** [comment] 2018-11-05 18:06
As we discussed at the kick-off meeting, we are likely best to go forward with the Landsat-based [CEC Land Cover 2010](http://www.cec.org/tools-and-resources/map-files/land-cover-2010-landsat-30m) land use raster. This can be integrated into the CRIM infra as soon as Thursday.

**Comment by tomLandry** [comment] 2018-11-05 18:08
Well that's beautiful, because CEC and NRCan!

**Comment by Zeitsperre** [comment] 2018-11-09 20:50
I've managed to upload the CEC LandCover 2010 dataset to one of the crim testing servers (starts with a 'c') but the data is in a custom projection so I had to add a new custom CRS definition (100004) to the geoserver's `epsg.properties`. In order for it to load, the geoserver instance needs to be restarted. If someone could restart the geoserver, I can confirm that the land use data is working and we can close this issue.

@ldperron could you restart the geoserver?

**Comment by richardarsenault** [comment] 2018-11-09 21:47
Excellent, thanks Trevor! 
Have a great weekend! 
Richard 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Trevor James Smith <notifications@github.com> Date: 2018-11-09  15:50  (GMT-05:00) To: Ouranosinc/raven <raven@noreply.github.com> Cc: richardarsenault <richard.arsenault@etsmtl.ca>, Mention <mention@noreply.github.com> Subject: Re: [Ouranosinc/raven] Upload land-use raster database to GeoServer (2) (#3) 
I've managed to upload the CEC LandCover 2010 dataset to one of the crim testing servers (starts with a 'c') but the data is in a custom projection so I had to add a new custom CRS definition (100004) to the geoserver's epsg.properties. In order for it to load, the geoserver instance needs to be restarted. If someone could restart the geoserver, I can confirm that the land use data is working and we can close this issue.
@ldperron could you restart the geoserver?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ouranosinc/raven","title":"Ouranosinc/raven","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Ouranosinc/raven"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Zeitsperre in #3: I've managed to upload the CEC LandCover 2010 dataset to one of the crim testing servers (starts with a 'c') but the data is in a custom projection so I had to add a new custom CRS definition (100004) to the geoserver's `epsg.properties`. In order for it to load, the geoserver instance needs to be restarted. If someone could restart the geoserver, I can confirm that the land use data is working and we can close this issue.\r\n\r\n@ldperron could you restart the geoserver?"}],"action":{"name":"View Issue","url":"https://github.com/Ouranosinc/raven/issues/3#issuecomment-437490951"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ouranosinc/raven/issues/3#issuecomment-437490951",
"url": "https://github.com/Ouranosinc/raven/issues/3#issuecomment-437490951",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Ouranosinc/raven] Upload land-use raster database to GeoServer (2) (#3)",
"sections": [
{
"text": "",
"activityTitle": "**Trevor James Smith**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Zeitsperre",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Ouranosinc/raven\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Ouranosinc/raven\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Ouranosinc/raven/issues/3#issuecomment-437490951"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340848294\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by richardarsenault** [comment] 2018-11-23 20:05
@Zeitsperre Hi, any news on this front?

**Comment by Zeitsperre** [comment] 2018-11-26 15:37
@richardarsenault I'm still waiting to hear back from CRIM. I just asked on slack if someone could perform the last step to verify that it works. I'll let you know by tomorrow.

**Comment by Zeitsperre** [comment] 2018-11-28 21:07
It's been updated and it seems to be working. The data simply needs to be synced between servers at CRIM and we should be able to cross this off.

**Comment by huard** [comment] 2019-04-18 19:32
@Zeitsperre Status ?

**Comment by huard** [comment] 2019-04-18 19:33
@Zeitsperre Status ?

**Comment by Zeitsperre** [comment] 2019-04-23 14:47
@huard The raster is present on a CRIM testing server. I'm blocked at the moment on the Ouranos production server as the layer uses a custom projection that needs to be configured within the GeoServer files. I need to wait on @moulab88 to create a `user_projections` folder within `/data/geoserver` folder that I have write access to before I can get the layer online.

**Comment by Zeitsperre** [comment] 2019-05-03 18:42
Fixed with #112

**Closed by Zeitsperre** 2019-05-03 18:42 UTC
Labels: blocker
